language: c++
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libglew-dev
            - libopenal-dev
cache:
  apt: true
  directories:
  - "$HOME/.travis/cmake/build/install"
  - "build"
  - "deps"

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-6; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-6; fi
  - pushd . && cd $HOME
  - git clone https://github.com/LB--/travis.git travis
  - source "./travis/update-cmake.sh"
  - popd

install:
  - pushd .
  - popd

script:
  - git submodule foreach 'git add --all && git reset --hard'
  - git add --all && git reset --hard
  - if [ ! -d "build/install" ]; then export FROM_SCRATCH="yes"; else export FROM_SCRATCH="no"; fi
  - mkdir -p build && cd build
  - export PATH="$(pwd)/install/bin:$PATH"
  - export LD_LIBRARY_PATH="$(pwd)/install/lib:$LD_LIBRARY_PATH"
  - if [ "$FROM_SCRATCH" == "yes" ]; then cmake .. -DCMAKE_INSTALL_PREFIX="$(pwd)/install"; fi
  - cmake --build .

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7500cccaf49dbeede3f4
    on_success: change
    on_failure: always
    on_start: never
